/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

//noobie noob noop

import Cocktail.*;

import function.*;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet; 
import SQL.javaconnect;
import javax.swing.*;


/**
 *
 * @author Dennis
 */
public class Hauptansichtneu extends javax.swing.JFrame {

    /**
     * Creates new form Hauptansichtneu
 */
   
    
    private int AktuellAngezeigerCocktail=0;
    private int zuletztGeoeffneterAlkCocktail=3;
    private int zuleztGeoeffneterNichtAlkCoktail=2;
    private int Ansicht;
    private Cocktail[][] AlkCocktail = new Cocktail[60][3];
    private Cocktail[][] keinAlkCocktail = new Cocktail[60][3];
    public static final String BasisPfad="/home/malte/Workspace6/cocktailmaschine/JavaApplication3";
    private int AnzahlAlk;
    private int AnzahlkeinAlk;
    private boolean zurzeitAlk;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst=null;
    
    
    public Hauptansichtneu() {
        conn=javaconnect.ConnectDb();
        setCocktails();
        System.err.println("test: "+AlkCocktail[40]);
        initComponents();
        Getränke.setVisible(false);      
        Ausgabefenster.setVisible(false);
        Loginpanel.setVisible(false);    
        Adminbereich.setVisible(false); 
        adminhinzu.setVisible(false);
        cocktailhinzu.setVisible(false);
    }
    
    /**
     *  Ordnet die Cocktails dem Alkoholischen und den Nicht Alkoholischen
     *  Puffer zu 
     *  
     *  muss aufgegrufen nach dem laden eines neuen rezeptes
     *  @return void 
     */
    private void setCocktails(){
        Ansicht=1;
        Cocktail[] alleCocktails = new Cocktail[60];    
        try{
          LoadBufferedCocktails load = new LoadBufferedCocktails();
          alleCocktails=load.alleCocktailsErzeugen();
        }
        catch (IOException e){
            System.out.println(e.getMessage());
        }        
        System.out.println("-----------------------------");
        int alk=0;
        int alk1=0;
        int keinalk=0;
        int keinalk1=0;
        try{
          for (int i=0; i<60; i++){
              System.out.println(alleCocktails[i].getBoolalk());
              if (alleCocktails[i].getBoolalk()==true){
                  System.out.println("ALK "+alleCocktails[i].getName());
                  AlkCocktail[alk][alk1]=alleCocktails[i];
                  System.out.println("ALK "+AlkCocktail[alk][alk1].getName());
                  AnzahlAlk++;
                  if(alk1==2){
                      alk1=0;
                      alk++;
                  }
                  else{
                      alk1++;
                  }
              }
              if (alleCocktails[i].getBoolalk()==false) {
                  System.out.println("keinALK "+alleCocktails[i].getName());
                  keinAlkCocktail[keinalk][keinalk1]=alleCocktails[i];
                  System.out.println("keinALK "+keinAlkCocktail[keinalk][keinalk1].getName());
                  AnzahlkeinAlk++;
                  if(keinalk1==2){
                      keinalk1=0;
                      keinalk++;
                  }
                  else{
                      keinalk1++;
                  }
                }
            }
        }
        catch (NullPointerException e){
            System.err.println(e.getMessage());
            System.out.println("alle Cocktails eingelesen");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adminbereich = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        adminhinzu = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        Vornametextfeld = new javax.swing.JTextField();
        nachnametextfeld = new javax.swing.JTextField();
        geburtstextfeld = new javax.swing.JTextField();
        Passworttextfeld = new javax.swing.JTextField();
        Geschlechttextfeld = new javax.swing.JComboBox();
        wohntextfeld = new javax.swing.JTextField();
        Benutzernametextfeld = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cocktailhinzu = new javax.swing.JPanel();
        zurück5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Hauptseite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Loginadminbutton = new javax.swing.JButton();
        AlkoholischeCocktailsButton = new javax.swing.JButton();
        BenutzerdefinierteCocktailsButton = new javax.swing.JButton();
        AlkoholfreieCocktailsButton = new javax.swing.JButton();
        Getränke = new javax.swing.JPanel();
        coc123 = new javax.swing.JPanel();
        AlkCocktail1 = new javax.swing.JButton();
        AlkCocktail2 = new javax.swing.JButton();
        AlkCocktail3 = new javax.swing.JButton();
        Label2 = new javax.swing.JLabel();
        zurück = new javax.swing.JButton();
        try {
            linksButton =(javax.swing.JToggleButton)java.beans.Beans.instantiate(getClass().getClassLoader(), "Gui.Hauptansichtneu_linksButton");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        rechtsButton = new javax.swing.JToggleButton();
        Ausgabefenster = new javax.swing.JPanel();
        Textfeld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zurückAusgabefenster = new javax.swing.JButton();
        BestellButton = new javax.swing.JButton();
        Loginpanel = new javax.swing.JPanel();
        Loginfenster = new javax.swing.JPanel();
        Eingangsbuttonadmin = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        benutzername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        zurücklogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("alpha");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1390, 768));
        setMinimumSize(new java.awt.Dimension(1390, 768));
        setResizable(false);

        Adminbereich.setMaximumSize(new java.awt.Dimension(1390, 768));
        Adminbereich.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Neuen Cocktail hinzufügen");
        Adminbereich.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 230, 40));

        jButton2.setText("Neuen Admin hinzufügen");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Adminbereich.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 210, 40));

        adminhinzu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextField3.setText("Vorname:");
        jTextField3.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField3.setEnabled(false);

        jTextField4.setText("Nachname:");
        jTextField4.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField4.setEnabled(false);

        jTextField5.setText("Geschlecht:");
        jTextField5.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField5.setEnabled(false);

        jTextField7.setText("Geburtsdatum (TTMMJJ):");
        jTextField7.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField7.setEnabled(false);

        jTextField8.setText("Benutzername:");
        jTextField8.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField8.setEnabled(false);
        jTextField8.setFocusable(false);

        jTextField9.setText("Passwort:");
        jTextField9.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField9.setEnabled(false);

        jTextField10.setText("Wohnort:");
        jTextField10.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jTextField10.setEnabled(false);

        Vornametextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VornametextfeldActionPerformed(evt);
            }
        });

        nachnametextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nachnametextfeldActionPerformed(evt);
            }
        });

        Passworttextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassworttextfeldActionPerformed(evt);
            }
        });

        Geschlechttextfeld.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                     ", "männlich", "weiblich" }));
        Geschlechttextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeschlechttextfeldActionPerformed(evt);
            }
        });

        wohntextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wohntextfeldActionPerformed(evt);
            }
        });

        Benutzernametextfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenutzernametextfeldActionPerformed(evt);
            }
        });

        jButton3.setText("Registrieren");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminhinzuLayout = new javax.swing.GroupLayout(adminhinzu);
        adminhinzu.setLayout(adminhinzuLayout);
        adminhinzuLayout.setHorizontalGroup(
            adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminhinzuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(adminhinzuLayout.createSequentialGroup()
                        .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminhinzuLayout.createSequentialGroup()
                                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Benutzernametextfeld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Passworttextfeld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adminhinzuLayout.createSequentialGroup()
                                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(geburtstextfeld, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(nachnametextfeld)
                                    .addComponent(Vornametextfeld)
                                    .addComponent(Geschlechttextfeld, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wohntextfeld, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminhinzuLayout.setVerticalGroup(
            adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminhinzuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vornametextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nachnametextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Geschlechttextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geburtstextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wohntextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benutzernametextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Passworttextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Adminbereich.add(adminhinzu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 600, -1));

        cocktailhinzu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cocktailhinzu.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout cocktailhinzuLayout = new javax.swing.GroupLayout(cocktailhinzu);
        cocktailhinzu.setLayout(cocktailhinzuLayout);
        cocktailhinzuLayout.setHorizontalGroup(
            cocktailhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        cocktailhinzuLayout.setVerticalGroup(
            cocktailhinzuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        Adminbereich.add(cocktailhinzu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 290));

        zurück5.setText("jButton4");
        zurück5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurück5ActionPerformed(evt);
            }
        });
        Adminbereich.add(zurück5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/adminhintergrund.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1390, 768));
        jLabel7.setMinimumSize(new java.awt.Dimension(1390, 768));
        Adminbereich.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 790));

        Hauptseite.setPreferredSize(new java.awt.Dimension(1390, 768));
        Hauptseite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/StartHintergrund.jpg"))); // NOI18N
        Hauptseite.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        Loginadminbutton.setText("jButton2");
        Loginadminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginadminbuttonActionPerformed(evt);
            }
        });
        Hauptseite.add(Loginadminbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1234, 718, 150, 40));

        AlkoholischeCocktailsButton.setText("Alkoholische Cocktails");
        AlkoholischeCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholischeCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholischeCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 100));

        BenutzerdefinierteCocktailsButton.setText("Benutzerdefinierte Cocktails");
        Hauptseite.add(BenutzerdefinierteCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 390, 120));

        AlkoholfreieCocktailsButton.setText("Alkoholfreie Cocktails");
        AlkoholfreieCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholfreieCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholfreieCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 380, 110));

        Getränke.setMinimumSize(new java.awt.Dimension(1390, 768));
        Getränke.setPreferredSize(new java.awt.Dimension(1390, 768));
        Getränke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coc123.setDoubleBuffered(false);
        coc123.setEnabled(false);
        coc123.setFocusable(false);
        coc123.setOpaque(false);

        AlkCocktail1.setBorder(null);
        AlkCocktail1.setBorderPainted(false);
        AlkCocktail1.setContentAreaFilled(false);
        AlkCocktail1.setDefaultCapable(false);
        AlkCocktail1.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail1ActionPerformed(evt);
            }
        });

        AlkCocktail2.setBorder(null);
        AlkCocktail2.setBorderPainted(false);
        AlkCocktail2.setContentAreaFilled(false);
        AlkCocktail2.setDefaultCapable(false);
        AlkCocktail2.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail2ActionPerformed(evt);
            }
        });

        AlkCocktail3.setBorder(null);
        AlkCocktail3.setBorderPainted(false);
        AlkCocktail3.setContentAreaFilled(false);
        AlkCocktail3.setDefaultCapable(false);
        AlkCocktail3.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coc123Layout = new javax.swing.GroupLayout(coc123);
        coc123.setLayout(coc123Layout);
        coc123Layout.setHorizontalGroup(
            coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coc123Layout.createSequentialGroup()
                .addComponent(AlkCocktail1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(AlkCocktail2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(AlkCocktail3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        coc123Layout.setVerticalGroup(
            coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coc123Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AlkCocktail2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlkCocktail1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(AlkCocktail3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        Getränke.add(coc123, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 300));

        Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Cocktailhintergrund.jpg"))); // NOI18N
        Label2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Label2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Label2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Getränke.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        zurück.setText("Zürück");
        zurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückActionPerformed(evt);
            }
        });
        Getränke.add(zurück, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, 50));

        linksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linksButtonActionPerformed(evt);
            }
        });
        Getränke.add(linksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 120, 130));

        rechtsButton.setText("rechtsButton");
        rechtsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechtsButtonMouseClicked(evt);
            }
        });
        rechtsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechtsButtonActionPerformed(evt);
            }
        });
        Getränke.add(rechtsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 530, 140, 160));

        Ausgabefenster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Textfeld.setEditable(false);
        Textfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfeldActionPerformed(evt);
            }
        });
        Ausgabefenster.add(Textfeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 450, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/bestellhintergrund.jpg"))); // NOI18N
        Ausgabefenster.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        zurückAusgabefenster.setText("Zürück");
        zurückAusgabefenster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückAusgabefensterActionPerformed(evt);
            }
        });
        Ausgabefenster.add(zurückAusgabefenster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        BestellButton.setText("Bestellen");
        BestellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestellButtonActionPerformed(evt);
            }
        });
        Ausgabefenster.add(BestellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, 160, 40));

        Loginpanel.setPreferredSize(new java.awt.Dimension(1390, 768));
        Loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginfenster.setBackground(new java.awt.Color(195, 184, 172));
        Loginfenster.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        Loginfenster.setForeground(new java.awt.Color(234, 180, 180));
        Loginfenster.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Loginfenster.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Loginfenster.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N

        Eingangsbuttonadmin.setText("Login");
        Eingangsbuttonadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EingangsbuttonadminActionPerformed(evt);
            }
        });

        benutzername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benutzernameActionPerformed(evt);
            }
        });

        jLabel5.setText("Benutzername:");

        jLabel6.setText("Passwort");

        javax.swing.GroupLayout LoginfensterLayout = new javax.swing.GroupLayout(Loginfenster);
        Loginfenster.setLayout(LoginfensterLayout);
        LoginfensterLayout.setHorizontalGroup(
            LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginfensterLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(benutzername))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginfensterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eingangsbuttonadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        LoginfensterLayout.setVerticalGroup(
            LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginfensterLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(benutzername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Eingangsbuttonadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Loginpanel.add(Loginfenster, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 450, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/StartHintergrund.jpg"))); // NOI18N
        Loginpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        zurücklogin.setText("ZürückLoginfenster");
        zurücklogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückloginActionPerformed(evt);
            }
        });
        Loginpanel.add(zurücklogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1390, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hauptseite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Adminbereich, javax.swing.GroupLayout.DEFAULT_SIZE, 1414, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hauptseite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Adminbereich, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AlkoholischeCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholischeCocktailsButtonActionPerformed
        Ansicht=0;
        zurzeitAlk=true;
        setImageCocktail1(AlkCocktail[0][0].getName());
        setImageCocktail2(AlkCocktail[0][1].getName());
        setImageCocktail3(AlkCocktail[0][2].getName());            

        Getränke.setVisible(true);
        Hauptseite.setVisible(false);
    }//GEN-LAST:event_AlkoholischeCocktailsButtonActionPerformed
    
    /**
     * Ordnet dem Ersten Butten den Richtigen Cocktail zu
     * 
     * @param ID 
     * @return true wenn ein Cocktail gefunden wurde 
     *         false wenn nicht
     */
    private boolean setImageCocktail1(String Name){
        try{
            ImageIcon newImage;
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +Name
                                                 +".gif");
            AlkCocktail1.setIcon(newImage);
            AlkCocktail1.setEnabled(true);
            return true;
        }
        catch (NullPointerException e){
            AlkCocktail1.setEnabled(false);
            AlkCocktail1.setIcon(null);
            return false;
        }
        
    }
    
     /**
     * Ordnet dem Zweiten Butten den Richtigen Cocktail zu
     * 
     * @param ID 
     * @return true wenn ein Cocktail gefunden wurde 
     *         false wenn nicht
     */
    private boolean setImageCocktail2(String Name){
        try{
            ImageIcon newImage;
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +Name
                                                 +".gif");
            AlkCocktail2.setIcon(newImage);
            AlkCocktail2.setEnabled(true);
            return true;
        }
        catch (NullPointerException e){
            AlkCocktail2.setEnabled(false);
            AlkCocktail2.setIcon(null);
            return false;
        }
    }
    
    /**
     * Ordnet dem Dritten Butten den Richtigen Cocktail zu
     * 
     * @param ID 
     * @return true wenn ein Cocktail gefunden wurde 
     *         false wenn nicht
     */        
    private boolean setImageCocktail3(String Name) {
        try{
            ImageIcon newImage;
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +Name
                                                 +".gif");

            AlkCocktail3.setIcon(newImage);
            AlkCocktail3.setEnabled(true);
            return true;
        }
        catch (NullPointerException e){
            AlkCocktail3.setEnabled(false);
            AlkCocktail3.setIcon(null);
            return false;
        }
    }   
    
    private void AlkoholfreieCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholfreieCocktailsButtonActionPerformed
        Ansicht=0;
        zurzeitAlk=false;
        setImageCocktail1(keinAlkCocktail[0][0].getName());
        setImageCocktail2(keinAlkCocktail[0][1].getName());
        setImageCocktail3(keinAlkCocktail[0][2].getName());            

        Getränke.setVisible(true);
        Hauptseite.setVisible(false);    
        
    }//GEN-LAST:event_AlkoholfreieCocktailsButtonActionPerformed

    private void zurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückActionPerformed
        //Hauptansichtneu hauptansichtneu = new Hauptansichtneu();
        Getränke.setVisible(false);
        Hauptseite.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückActionPerformed

    private void zurückAusgabefensterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückAusgabefensterActionPerformed
        Ausgabefenster.setVisible(false);
        Getränke.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückAusgabefensterActionPerformed

    private void linksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButtonActionPerformed
        if(zurzeitAlk==true){    
            try{

                setImageCocktail1(AlkCocktail[Ansicht-1][0].getName());
                setImageCocktail2(AlkCocktail[Ansicht-1][1].getName());
                setImageCocktail3(AlkCocktail[Ansicht-1][2].getName());
                Ansicht--;
            }
            catch (NullPointerException e){
                Ansicht = (AnzahlAlk/3);
                if (AnzahlAlk%3==0)Ansicht--;
                int i=0;
                try{
                    setImageCocktail1(AlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail2(AlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail3(AlkCocktail[Ansicht][i].getName());
                }
                catch(NullPointerException f){
                    if(i<2){AlkCocktail2.setEnabled(false);
                             AlkCocktail2.setIcon(null);}
                    if(i<=2){AlkCocktail3.setEnabled(false);
                             AlkCocktail3.setIcon(null);}
                }
            }
            catch(ArrayIndexOutOfBoundsException e){
                Ansicht = (AnzahlAlk/3);
                if (AnzahlAlk%3==0)Ansicht--;
                int i=0;
                try{
                    setImageCocktail1(AlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail2(AlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail3(AlkCocktail[Ansicht][i].getName());
                }
                catch(NullPointerException f){
                    if(i<2){AlkCocktail2.setEnabled(false);
                             AlkCocktail2.setIcon(null);}
                    if(i<=2){AlkCocktail3.setEnabled(false);
                             AlkCocktail3.setIcon(null);}
                }
            }
        }
        //nichtalkoholische Kocktails
        if(zurzeitAlk==false){
            try{

                setImageCocktail1(keinAlkCocktail[Ansicht-1][0].getName());
                setImageCocktail2(keinAlkCocktail[Ansicht-1][1].getName());
                setImageCocktail3(keinAlkCocktail[Ansicht-1][2].getName());
                Ansicht--;
            }
            catch (NullPointerException e){
                Ansicht = (AnzahlkeinAlk/3)-1;
                setImageCocktail1(keinAlkCocktail[(AnzahlAlk/3)][0].getName());
                setImageCocktail2(keinAlkCocktail[(AnzahlAlk/3)][1].getName());
                setImageCocktail3(keinAlkCocktail[(AnzahlAlk/3)][2].getName());
            }
            catch(ArrayIndexOutOfBoundsException e){
                Ansicht = (AnzahlAlk/3);
                if (AnzahlAlk%3==0)Ansicht--;
                int i=0;
                try{
                    setImageCocktail1(keinAlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail2(keinAlkCocktail[Ansicht][i].getName());
                    i++;
                    setImageCocktail3(keinAlkCocktail[Ansicht][i].getName());
                }
                catch(NullPointerException f){
                    if(i<2){AlkCocktail2.setEnabled(false);
                             AlkCocktail2.setIcon(null);}
                    if(i<=2){AlkCocktail3.setEnabled(false);
                             AlkCocktail3.setIcon(null);}
                }
            }
            
        }
    }//GEN-LAST:event_linksButtonActionPerformed

    
    private void rechtsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechtsButtonActionPerformed
    int i=0;
        if(zurzeitAlk==true){
            Ansicht++;            
            try{
                setImageCocktail1(AlkCocktail[Ansicht][i].getName());
                i++;
                setImageCocktail2(AlkCocktail[Ansicht][i].getName());
                i++;
                setImageCocktail3(AlkCocktail[Ansicht][i].getName()); 
            }
            catch(NullPointerException e){
                if(i==0){
                AlkoholischeCocktailsButtonActionPerformed(null);                    
                }else{    
                    if(i<2){AlkCocktail2.setEnabled(false);
                             AlkCocktail2.setIcon(null);}
                    if(i<=2){AlkCocktail3.setEnabled(false);
                             AlkCocktail3.setIcon(null);}
                }
            }
        }
        if(zurzeitAlk==false){
            Ansicht++;
            try{
                setImageCocktail1(keinAlkCocktail[Ansicht][i].getName());
                i++;
                setImageCocktail2(keinAlkCocktail[Ansicht][i].getName());
                i++;
                setImageCocktail3(keinAlkCocktail[Ansicht][i].getName()); 
            }
            catch(NullPointerException e){
                if(i==0){
                AlkoholfreieCocktailsButtonActionPerformed(null);                    
                }else{    
                    if(i<2){AlkCocktail2.setEnabled(false);
                             AlkCocktail2.setIcon(null);}
                    if(i<=2){AlkCocktail3.setEnabled(false);
                             AlkCocktail3.setIcon(null);}
                }
            } 
        }
    }//GEN-LAST:event_rechtsButtonActionPerformed
    
    private void setAusgabefensterAlk(int ID){
        Textfeld.setText(AlkCocktail[Ansicht][ID].getName());
    }
    
    private void setAusgabefensterNichtAlk(int ID){
        Textfeld.setText(this.keinAlkCocktail[Ansicht][ID].getName());       
    }
        
    private void AlkCocktail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail1ActionPerformed
        if (zurzeitAlk==true){
            setAusgabefensterAlk(0);
        }
        if(zurzeitAlk==false){
            setAusgabefensterNichtAlk(0);
        }
        Getränke.setVisible(false);
        Ausgabefenster.setVisible(true);
        
    }//GEN-LAST:event_AlkCocktail1ActionPerformed

    private void TextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfeldActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_TextfeldActionPerformed

    private void BestellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestellButtonActionPerformed

    }//GEN-LAST:event_BestellButtonActionPerformed

    private void Label2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Label2AncestorAdded
           // TODO add your handling code here:
    }//GEN-LAST:event_Label2AncestorAdded

    private void AlkCocktail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail2ActionPerformed
        if (zurzeitAlk==true){
            setAusgabefensterAlk(1);
        }
        if(zurzeitAlk==false){
            setAusgabefensterNichtAlk(1);
        }
        Getränke.setVisible(false);
        Ausgabefenster.setVisible(true);
    }//GEN-LAST:event_AlkCocktail2ActionPerformed

    private void AlkCocktail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail3ActionPerformed
        if (zurzeitAlk==true){
            setAusgabefensterAlk(2);
        }
        if(zurzeitAlk==false){
            setAusgabefensterNichtAlk(2);
        }
        Getränke.setVisible(false);
        Ausgabefenster.setVisible(true); 
    }//GEN-LAST:event_AlkCocktail3ActionPerformed

    private void rechtsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechtsButtonMouseClicked

        
    }//GEN-LAST:event_rechtsButtonMouseClicked

    private void LoginadminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginadminbuttonActionPerformed
      Loginpanel.setVisible(true);
      Loginfenster.setVisible(true);
      Hauptseite.setVisible(false);
              // TODO add your handling code here:
    }//GEN-LAST:event_LoginadminbuttonActionPerformed

    private void linksButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linksButton1ActionPerformed

    private void nachnametextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nachnametextfeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nachnametextfeldActionPerformed

    private void PassworttextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassworttextfeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassworttextfeldActionPerformed

    private void GeschlechttextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeschlechttextfeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeschlechttextfeldActionPerformed

    private void wohntextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wohntextfeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wohntextfeldActionPerformed

    private void BenutzernametextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenutzernametextfeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BenutzernametextfeldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    adminhinzu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void zurück5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurück5ActionPerformed
       Adminbereich.setVisible(false);
        Hauptseite.setVisible(true);   
    }//GEN-LAST:event_zurück5ActionPerformed

    private void VornametextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VornametextfeldActionPerformed
    Benutzer benutzer  = new Benutzer();
    benutzer.setName(Action.NAME);
    }//GEN-LAST:event_VornametextfeldActionPerformed

    private void EingangsbuttonadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EingangsbuttonadminActionPerformed
        String sql1 ="select * From 'DENNIS' WHERE NAME=?";
        String sql2 ="select * From 'DENNIS' WHERE PASSWORT=?";

        try{
            //Username
            pst=conn.prepareStatement(sql1);
            pst.setString(1, benutzername.getText());
            rs=pst.executeQuery();
            //Passwort
            pst=conn.prepareStatement(sql2);
            pst.setString(1, jPasswordField1.getText());
            rs=pst.executeQuery();

            if (rs.next()){
                JOptionPane.showMessageDialog(null, "Connect");
                Adminbereich.setVisible(true);
                Loginpanel.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not Conntect (False Username or Password)");
                Adminbereich.setVisible(false);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EingangsbuttonadminActionPerformed

    private void benutzernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benutzernameActionPerformed

    }//GEN-LAST:event_benutzernameActionPerformed

    private void zurückloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückloginActionPerformed
        Loginpanel.setVisible(false);
        Hauptseite.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückloginActionPerformed

 public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
 try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
Hauptansichtneu neu = new Hauptansichtneu();
neu.setVisible(true);
}
});
}
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adminbereich;
    private javax.swing.JButton AlkCocktail1;
    private javax.swing.JButton AlkCocktail2;
    private javax.swing.JButton AlkCocktail3;
    private javax.swing.JButton AlkoholfreieCocktailsButton;
    private javax.swing.JButton AlkoholischeCocktailsButton;
    private javax.swing.JPanel Ausgabefenster;
    private javax.swing.JButton BenutzerdefinierteCocktailsButton;
    private javax.swing.JTextField Benutzernametextfeld;
    private javax.swing.JButton BestellButton;
    private javax.swing.JButton Eingangsbuttonadmin;
    private javax.swing.JComboBox Geschlechttextfeld;
    private javax.swing.JPanel Getränke;
    private javax.swing.JPanel Hauptseite;
    private javax.swing.JLabel Label2;
    private javax.swing.JButton Loginadminbutton;
    private javax.swing.JPanel Loginfenster;
    private javax.swing.JPanel Loginpanel;
    private javax.swing.JTextField Passworttextfeld;
    private javax.swing.JTextField Textfeld;
    private javax.swing.JTextField Vornametextfeld;
    private javax.swing.JPanel adminhinzu;
    private javax.swing.JTextField benutzername;
    private javax.swing.JPanel coc123;
    private javax.swing.JPanel cocktailhinzu;
    private javax.swing.JTextField geburtstextfeld;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton linksButton;
    private javax.swing.JTextField nachnametextfeld;
    private javax.swing.JToggleButton rechtsButton;
    private javax.swing.JTextField wohntextfeld;
    private javax.swing.JButton zurück;
    private javax.swing.JButton zurück5;
    private javax.swing.JButton zurückAusgabefenster;
    private javax.swing.JButton zurücklogin;
    // End of variables declaration//GEN-END:variables
}
