/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

//noobie noob noop

import Cocktail.*;
import function.*;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author Dennis
 */
public class Hauptansichtneu extends javax.swing.JFrame {

    /**
     * Creates new form Hauptansichtneu
 */
    private int AktuellAngezeigerCocktail=0;
    private int zuletztGeoeffneterAlkCocktail=3;
    private int zuleztGeoeffneterNichtAlkCoktail=3;
    private boolean zurzeitAlk;
    private Cocktail[] AlkCocktail = new Cocktail[60];
    private Cocktail[] keinAlkCocktail = new Cocktail [60];
    public static final String BasisPfad="/home/malte/Workspace3/cocktailmaschine/JavaApplication3";
    
    
    public Hauptansichtneu() {
        setCocktails();
        initComponents();
        Getränke.setVisible(false);      
        Ausgabefenster.setVisible(false);
        Loginfenster.setVisible(false);       
    }
    
    private void setCocktails(){
        Cocktail[] alleCocktails = new Cocktail[60];
        
        try{
          LoadBufferedCocktails load = new LoadBufferedCocktails();
          alleCocktails=load.alleCocktailsErzeugen();
          

         
        }
        catch (IOException e){
            System.out.println(e.getMessage());
        }
        
        System.out.println("-----------------------------");
        int alk=0;
        int keinalk=0;
        try{
          for (int i=0; i<60; i++){
              System.out.println(alleCocktails[i].getBoolalk());
              if (alleCocktails[i].getBoolalk()){
                  System.out.println(alk+"    alk :"+alleCocktails[i].getName());
                  AlkCocktail[alk]=alleCocktails[i];
                  System.out.println(AlkCocktail[alk].getName());
                  alk++;
              }
              else {
                  keinAlkCocktail[keinalk]=alleCocktails[i];
                  System.out.println(keinalk+"   kein alk:"+keinAlkCocktail[keinalk].getName());                  
                  keinalk++;
                }
            }
        }
        catch (NullPointerException e){
            System.err.println(e.getMessage());
            System.out.println("alle Cocktails eingelesen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hauptseite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Loginadminbutton = new javax.swing.JButton();
        AlkoholischeCocktailsButton = new javax.swing.JButton();
        BenutzerdefinierteCocktailsButton = new javax.swing.JButton();
        AlkoholfreieCocktailsButton = new javax.swing.JButton();
        Loginfenster = new javax.swing.JPanel();
        Loginzugang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        Getränke = new javax.swing.JPanel();
        coc123 = new javax.swing.JPanel();
        AlkCocktail1 = new javax.swing.JButton();
        AlkCocktail2 = new javax.swing.JButton();
        AlkCocktail3 = new javax.swing.JButton();
        Label2 = new javax.swing.JLabel();
        zurück = new javax.swing.JButton();
        try {
            linksButton =(javax.swing.JToggleButton)java.beans.Beans.instantiate(getClass().getClassLoader(), "Gui.Hauptansichtneu_linksButton");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        rechtsButton = new javax.swing.JToggleButton();
        Ausgabefenster = new javax.swing.JPanel();
        Textfeld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zurückAusgabefenster = new javax.swing.JButton();
        BestellButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("alpha");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1390, 768));
        setMinimumSize(new java.awt.Dimension(1390, 768));
        setResizable(false);

        Hauptseite.setPreferredSize(new java.awt.Dimension(1390, 768));
        Hauptseite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/StartHintergrund.jpg"))); // NOI18N
        Hauptseite.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        Loginadminbutton.setText("jButton2");
        Loginadminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginadminbuttonActionPerformed(evt);
            }
        });
        Hauptseite.add(Loginadminbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1234, 718, 150, 40));

        AlkoholischeCocktailsButton.setText("Alkoholische Cocktails");
        AlkoholischeCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholischeCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholischeCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 100));

        BenutzerdefinierteCocktailsButton.setText("Benutzerdefinierte Cocktails");
        Hauptseite.add(BenutzerdefinierteCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 390, 120));

        AlkoholfreieCocktailsButton.setText("Alkoholfreie Cocktails");
        AlkoholfreieCocktailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkoholfreieCocktailsButtonActionPerformed(evt);
            }
        });
        Hauptseite.add(AlkoholfreieCocktailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 380, 110));

        Loginfenster.setForeground(new java.awt.Color(226, 37, 37));
        Loginfenster.setPreferredSize(new java.awt.Dimension(1390, 768));

        Loginzugang.setText("Zugang");
        Loginzugang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginzugangActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/StartHintergrund.jpg"))); // NOI18N
        jLabel2.setVerifyInputWhenFocusTarget(false);

        jTextField1.setEditable(false);
        jTextField1.setText("Passwort:");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("Benutzername:");
        jTextField3.setEnabled(false);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTextField5.setText("Adminebene - Login");
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginfensterLayout = new javax.swing.GroupLayout(Loginfenster);
        Loginfenster.setLayout(LoginfensterLayout);
        LoginfensterLayout.setHorizontalGroup(
            LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginfensterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LoginfensterLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginfensterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(LoginfensterLayout.createSequentialGroup()
                        .addGap(1526, 1526, 1526)
                        .addComponent(Loginzugang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        LoginfensterLayout.setVerticalGroup(
            LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginfensterLayout.createSequentialGroup()
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginfensterLayout.createSequentialGroup()
                        .addComponent(Loginzugang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(LoginfensterLayout.createSequentialGroup()
                        .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginfensterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)))
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(LoginfensterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        Getränke.setMinimumSize(new java.awt.Dimension(1390, 768));
        Getränke.setPreferredSize(new java.awt.Dimension(1390, 768));
        Getränke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coc123.setDoubleBuffered(false);
        coc123.setEnabled(false);
        coc123.setFocusable(false);
        coc123.setOpaque(false);

        AlkCocktail1.setBorder(null);
        AlkCocktail1.setBorderPainted(false);
        AlkCocktail1.setContentAreaFilled(false);
        AlkCocktail1.setDefaultCapable(false);
        AlkCocktail1.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail1ActionPerformed(evt);
            }
        });

        AlkCocktail2.setBorder(null);
        AlkCocktail2.setBorderPainted(false);
        AlkCocktail2.setContentAreaFilled(false);
        AlkCocktail2.setDefaultCapable(false);
        AlkCocktail2.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail2ActionPerformed(evt);
            }
        });

        AlkCocktail3.setBorder(null);
        AlkCocktail3.setBorderPainted(false);
        AlkCocktail3.setContentAreaFilled(false);
        AlkCocktail3.setDefaultCapable(false);
        AlkCocktail3.setMaximumSize(new java.awt.Dimension(20, 23));
        AlkCocktail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlkCocktail3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coc123Layout = new javax.swing.GroupLayout(coc123);
        coc123.setLayout(coc123Layout);
        coc123Layout.setHorizontalGroup(
            coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coc123Layout.createSequentialGroup()
                .addComponent(AlkCocktail1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(AlkCocktail2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(AlkCocktail3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        coc123Layout.setVerticalGroup(
            coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coc123Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(coc123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AlkCocktail2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlkCocktail1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(AlkCocktail3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        Getränke.add(coc123, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 300));

        Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Cocktailhintergrund.jpg"))); // NOI18N
        Label2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Label2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Label2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Getränke.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        zurück.setText("Zürück");
        zurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückActionPerformed(evt);
            }
        });
        Getränke.add(zurück, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, 50));

        linksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linksButtonActionPerformed(evt);
            }
        });
        Getränke.add(linksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 130));

        rechtsButton.setText("rechtsButton");
        rechtsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechtsButtonMouseClicked(evt);
            }
        });
        rechtsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechtsButtonActionPerformed(evt);
            }
        });
        Getränke.add(rechtsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 530, 140, 160));

        Ausgabefenster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Textfeld.setEditable(false);
        Textfeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfeldActionPerformed(evt);
            }
        });
        Ausgabefenster.add(Textfeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 450, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/bestellhintergrund.jpg"))); // NOI18N
        Ausgabefenster.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 768));

        zurückAusgabefenster.setText("Zürück");
        zurückAusgabefenster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zurückAusgabefensterActionPerformed(evt);
            }
        });
        Ausgabefenster.add(zurückAusgabefenster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        BestellButton.setText("Bestellen");
        BestellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestellButtonActionPerformed(evt);
            }
        });
        Ausgabefenster.add(BestellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hauptseite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Loginfenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hauptseite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Getränke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Loginfenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ausgabefenster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlkoholischeCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholischeCocktailsButtonActionPerformed
        zurzeitAlk=true;
        setImageCocktail1(zuletztGeoeffneterAlkCocktail-3);
        setImageCocktail2(zuletztGeoeffneterAlkCocktail-2);
        setImageCocktail3(zuletztGeoeffneterAlkCocktail-1);
        Getränke.setVisible(true);
        Hauptseite.setVisible(false);
    }//GEN-LAST:event_AlkoholischeCocktailsButtonActionPerformed

    private void setImageCocktail1(int ID){
        try{
            ImageIcon newImage;
            if(zurzeitAlk){
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +AlkCocktail[ID].getName()
                                                 +".gif");

            }
            else{
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +keinAlkCocktail[ID].getName()
                                                 +".gif");                
            }
            AlkCocktail1.setIcon(newImage);
            AlkCocktail1.setEnabled(true);
        }
        catch (NullPointerException e){
            System.out.println("kein bild für die ID: "+ID);
            AlkCocktail1.setEnabled(false);
            AlkCocktail1.setIcon(null);
        }
    }
    
        private void setImageCocktail2(int ID){
        try{
            ImageIcon newImage;
            if(zurzeitAlk){
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +AlkCocktail[ID].getName()
                                                 +".gif");

            }
            else{
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +keinAlkCocktail[ID].getName()
                                                 +".gif");                
            }
            AlkCocktail2.setIcon(newImage);
            AlkCocktail2.setEnabled(true);
        }
        catch (NullPointerException e){
            System.out.println("kein bild für die ID: "+ID);
            AlkCocktail2.setEnabled(false);
            AlkCocktail2.setIcon(null);
        }
    }
        
    private void setImageCocktail3(int ID){
        try{
            ImageIcon newImage;
            if(zurzeitAlk){
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +AlkCocktail[ID].getName()
                                                 +".gif");

            }
            else{
                newImage= new ImageIcon(BasisPfad+"/Cocktails/Bilder/"
                                                 +keinAlkCocktail[ID].getName()
                                                 +".gif");                
            }
            AlkCocktail3.setIcon(newImage);
            AlkCocktail3.setEnabled(true);
        }
        catch (NullPointerException e){
            System.out.println("kein bild für die ID: "+ID);
            AlkCocktail3.setEnabled(false);
            AlkCocktail3.setIcon(null);
        }
    }   
    
    private void AlkoholfreieCocktailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkoholfreieCocktailsButtonActionPerformed
        zurzeitAlk=false;
        setImageCocktail1(zuleztGeoeffneterNichtAlkCoktail-3);
        setImageCocktail2(zuleztGeoeffneterNichtAlkCoktail-2);
        setImageCocktail3(zuleztGeoeffneterNichtAlkCoktail-1);
        Getränke.setVisible(true);
        Hauptseite.setVisible(false); 
           
        
    }//GEN-LAST:event_AlkoholfreieCocktailsButtonActionPerformed

    private void zurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückActionPerformed
        //Hauptansichtneu hauptansichtneu = new Hauptansichtneu();
        Getränke.setVisible(false);
        Hauptseite.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückActionPerformed

    private void zurückAusgabefensterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zurückAusgabefensterActionPerformed
        Ausgabefenster.setVisible(false);
        Getränke.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_zurückAusgabefensterActionPerformed

    private void linksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButtonActionPerformed
    
    }//GEN-LAST:event_linksButtonActionPerformed

    
    private void rechtsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechtsButtonActionPerformed

    }//GEN-LAST:event_rechtsButtonActionPerformed
        
        
    private void AlkCocktail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail1ActionPerformed
        Ausgabefenster.setVisible(true);
        Getränke.setVisible(false);
        
        /*        Cocktail eins = null;
        try {
        eins = load.CocktailErzeugen(1);
        }
        catch (IIOException a){
            
        }*/
        AktuellAngezeigerCocktail=1;
        Textfeld.setText(AlkCocktail[0].getName()+ " " +AlkCocktail[0].getPrintRezept(0));
        //eins.getRezept();
    }//GEN-LAST:event_AlkCocktail1ActionPerformed

    private void TextfeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfeldActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_TextfeldActionPerformed

    private void BestellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestellButtonActionPerformed
        // TODO add your handling code here:
        
       /* ModbusPrint newModbusPrint =new ModbusPrint(alleCocktails[AktuellAngezeigerCocktail-1].getRezept());
       try{
        newModbusPrint.printSPS();
       }
       catch (IOException a){
           System.out.println(a.getMessage());
       }*/
    }//GEN-LAST:event_BestellButtonActionPerformed

    private void Label2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Label2AncestorAdded
           // TODO add your handling code here:
    }//GEN-LAST:event_Label2AncestorAdded

    private void AlkCocktail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail2ActionPerformed
    Ausgabefenster.setVisible(true);
    Getränke.setVisible(false); 
    AktuellAngezeigerCocktail=2;
    Textfeld.setText(AlkCocktail[1].getName()+ " " +AlkCocktail[1].getPrintRezept(1));
    }//GEN-LAST:event_AlkCocktail2ActionPerformed

    private void AlkCocktail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkCocktail3ActionPerformed
    
    Ausgabefenster.setVisible(true);
    Getränke.setVisible(false); 
    AktuellAngezeigerCocktail=3;
    Textfeld.setText(AlkCocktail[2].getName()+ " " +AlkCocktail[2].getPrintRezept(2)); 
    }//GEN-LAST:event_AlkCocktail3ActionPerformed

    private void rechtsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechtsButtonMouseClicked

        
    }//GEN-LAST:event_rechtsButtonMouseClicked

    private void LoginadminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginadminbuttonActionPerformed
      Loginfenster.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_LoginadminbuttonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void LoginzugangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginzugangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginzugangActionPerformed

    private void linksButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linksButton1ActionPerformed

 public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
        break;
         }
    }       
    } catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
    java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
    java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(Hauptansichtneu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hauptansichtneu neu = new Hauptansichtneu();
                neu.setVisible(true);
                }
            });
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlkCocktail1;
    private javax.swing.JButton AlkCocktail2;
    private javax.swing.JButton AlkCocktail3;
    private javax.swing.JButton AlkoholfreieCocktailsButton;
    private javax.swing.JButton AlkoholischeCocktailsButton;
    private javax.swing.JPanel Ausgabefenster;
    private javax.swing.JButton BenutzerdefinierteCocktailsButton;
    private javax.swing.JButton BestellButton;
    private javax.swing.JPanel Getränke;
    private javax.swing.JPanel Hauptseite;
    private javax.swing.JLabel Label2;
    private javax.swing.JButton Loginadminbutton;
    private javax.swing.JPanel Loginfenster;
    private javax.swing.JButton Loginzugang;
    private javax.swing.JTextField Textfeld;
    private javax.swing.JPanel coc123;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton linksButton;
    private javax.swing.JToggleButton rechtsButton;
    private javax.swing.JButton zurück;
    private javax.swing.JButton zurückAusgabefenster;
    // End of variables declaration//GEN-END:variables
}